name: employment_attendance
description: A company employment attendance application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  provider: ^6.1.2
  intl: ^0.19.0
  dio: ^5.4.0
  go_router: ^14.1.0
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
